### ISSUE TITLE
Checklist for 1.0

### ISSUE THREAD

**Issue by retrixe** [retrixe/nbt#1]
- [ ] Write tests
- [ ] Write docs
- [ ] Benchmark performance
- [ ] Perhaps use `"type": "module"`
- [ ] Update ESLint configuration to v9
- [ ] Publish to npm :tada:
